### ISSUE TITLE
Add ...

### ISSUE THREAD

**Issue by KarimElHouari** [ansys/pydyna#135]
### 📝 Description of the feature

We would like to use DPF to post-process LS-DYNA results. These results are from the electrophysiology solver and are available in “post->Extend->EM node” in LS-PREPOST.
![image](https://user-images.githubusercontent.com/56921087/228815952-96ee5bc3-cc97-4743-a3c3-fe1ec7a730a1.png)

**Comment by wenhuiuy** [comment]
this feature request should go to https://github.com/ansys/pydpf-core/issues

**Comment by KarimElHouari** [comment]
Indeed, and it was added in the 24.0 version of the dpf server. Thanks.
