### ISSUE TITLE
Rigidwall motion card bug

### ISSUE THREAD

**Issue by kanthadya** [ansys/pydyna#275]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

This function is not setting the right value for OPT in RIGIDWALL_GEOMETRIC_MOTION
cyl_indentor.set_motion(Curve(x=[0, 10.0], y=[0, 5.94]), motion=Motion.ACCELERATION,dir=Direction(0, 0, -1))

### 📝 Steps to reproduce

cyl_indentor.set_motion(Curve(x=[0, 10.0], y=[0, 5.94]), motion=Motion.ACCELERATION,dir=Direction(0, 0, -1))

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

0.4.1

### 🐍 Which Python version are you using?

3.7

### 📦 Installed packages

```shell
---
```

**Comment by zhangzhanqun** [comment]
This problem has been resolved in the version 0.4.2
