### ISSUE TITLE
Can not fiind the path pyDyna/src/ansys/dyna/core/pre/Server

### ISSUE THREAD

**Issue by kakemoto** [ansys/pydyna#329]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

We were able to install the pyDyna package, pre server, and solver server and confirm startup.
I am trying to run the airbag sample following the instructions at the following URL
< https://dyna.docs.pyansys.com/version/stable//examples/Airbag/airbag_deploy.html#sphx-glr-examples-airbag-airbag-deploy-py >
However, the path listed on the same page,
< pyDyna/src/ansys/dyna/core/pre/Server>
and the file
<kwserver.py>
are not found.
Where are these paths and files located?

### 📝 Steps to reproduce

The procewere, was
python -m pip install ansys-pydyna-core
It was all.
After doing this operation, the folders and files could not be found, so the following operations were performed.
python -m pip install pyansys
python -m pip install ansys-pydyna-core
pip install ansys-dpf-post
But the situation did not change.

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

LS-DYNA R13.1.1

### 🐍 Which Python version are you using?

3.11

### 📦 Installed packages

```shell
ansys-api-dyna==0.3.2
ansys-api-fluent==0.3.12
ansys-api-mapdl==0.5.1
ansys-api-mechanical==0.1.0
ansys-api-meshing-prime==0.1.1
ansys-api-platform-instancemanagement==1.0.0
ansys-api-pyensight==0.3.0
ansys-api-sherlock==0.1.14
ansys-api-systemcoupling==0.1.0
ansys-dpf-composites==0.2.0
ansys-dpf-core==0.8.1
ansys-dpf-gate==0.3.1
ansys-dpf-gatebin==0.4.1
ansys-dpf-post==0.4.0
ansys-dyna-core==0.4.0
ansys-dynamicreporting-core==0.4.0
ansys-fluent-core==0.14.0
ansys-grantami-bomanalytics==1.1.3
ansys-grantami-bomanalytics-openapi==1.0.0
ansys-grantami-recordlists==1.0.0
ansys-grantami-serverapi-openapi==1.0.0
ansys-grpc-dpf==0.8.1
ansys-mapdl-core==0.64.1
ansys-mapdl-reader==0.52.20
ansys-math-core==0.1.1
ansys-mechanical-core==0.8.0
ansys-meshing-prime==0.4.1
ansys-motorcad-core==0.1.3
ansys-openapi-common==1.2.1
ansys-optislang-core==0.2.1
ansys-platform-instancemanagement==1.1.1
ansys-pyensight-core==0.5.3
ansys-pythonnet==3.1.0rc1
ansys-seascape==0.2.0
ansys-sherlock-core==0.2.0
ansys-systemcoupling-core==0.1.3
appdirs==1.4.4
asgiref==3.7.2
build==1.0.3
cachetools==5.3.2
certifi==2023.7.22
cffi==1.16.0
charset-normalizer==3.3.1
click==8.1.7
clr-loader==0.2.6
colorama==0.4.6
contourpy==1.2.0
cryptography==41.0.5
cycler==0.12.1
Django==4.2.7
docutils==0.20.1
filelock==3.13.1
fonttools==4.44.3
google-api-core==2.12.0
google-api-python-client==2.105.0
google-auth==2.23.3
google-auth-httplib2==0.1.1
googleapis-common-protos==1.61.0
grpcio==1.59.0
grpcio-status==1.48.2
h5py==3.10.0
httplib2==0.22.0
idna==3.4
importlib-metadata==6.8.0
jaraco.classes==3.3.0
keyring==24.3.0
kiwisolver==1.4.5
lxml==4.9.3
markdown-it-py==3.0.0
matplotlib==3.8.1
mdurl==0.1.2
more-itertools==10.1.0
nh3==0.2.14
numpy==1.26.1
packaging==23.2
pandas==2.1.3
Pillow==10.1.0
pkginfo==1.9.6
platformdirs==4.0.0
plumbum==1.8.2
pooch==1.8.0
protobuf==3.20.3
psutil==5.9.6
pyaedt==0.6.76
pyansys==2023.2.11
pyansys-docker==5.0.4
pyansys-tools-versioning==0.5.0
pyasn1==0.5.0
pyasn1-modules==0.3.0
pycparser==2.21
Pygments==2.16.1
pyiges==0.3.1
pyparsing==3.1.1
pypiwin32==223
pypng==0.20220715.0
pyproject_hooks==1.0.0
pyspnego==0.10.2
python-dateutil==2.8.2
pythonnet==3.0.1
pytwin==0.3.0
pytz==2023.3.post1
pyvista==0.42.3
pywin32==306
pywin32-ctypes==0.2.2
PyYAML==6.0.1
readme-renderer==42.0
requests==2.31.0
requests-negotiate-sspi==0.5.2
requests-ntlm==1.2.0
requests-toolbelt==1.0.0
rfc3986==2.0.0
rich==13.7.0
rpyc==5.3.1
rsa==4.9
scipy==1.11.3
scooby==0.9.2
six==1.16.0
sqlparse==0.4.4
sspilib==0.1.0
tqdm==4.66.1
twine==4.0.2
typing==3.7.4.3
typing_extensions==4.8.0
tzdata==2023.3
uritemplate==4.1.1
urllib3==1.26.18
vtk==9.3.0
websocket-client==1.6.4
zipp==3.17.0
```

**Comment by RobPasMue** [comment]
@ansys/pydyna - please review this user's request

**Comment by wenhuiuy** [comment]
if you have already startup the pre server, please ignore this step "Manually start the pre service", we must have forgotten update this example page. will update later.

**Comment by kakemoto** [comment]
Thank you for the reply. I will try it as soon as possible.

**Comment by kakemoto** [comment]
I tested the connection to the pyDyna pre server using 'pydyna-main\examples\Airbag\airbag_deploy.py'.
The pre server was started as follows

PS D:\> docker run -d -p 50051:50051 ghcr.io/ansys/ls-pre:Pre01
5fcabb8192a458fc2cb94fcbea305281c28e8cbf16937ab0b536014fdf781b86

The following is the status of the Linux component.

CONTAINER ID IMAGE COMMAND CREATED STATUS PORTS NAMES
5fcabb8192a4 ghcr.io/ansys/ls-pre:Pre01 "python3 . /linux-bin..." 16 minutes ago Up 16 minutes 0.0.0.0:50051->50051/tcp silly_aryabhata

I tried running airbag_deploy.py in pydyna-main\examples\Airbag folder in Github and got the following error

(pydyna) PS D:\Projects\R&D\pydyna-main\examples\Airbag> python . \airbag_deploy.py
Exception in thread Thread-5:.
Traceback (most recent call last):.
  File "C:\Users\t321242\.pyenv\pyenv-win\versions\3.11.4\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "D:\venv\pydyna\Lib\site-packages\ansys\dyna\core\pre\launcher.py", line 123, in run
    self.process = launch_grpc(ip=self.ip, port=self.port, server_path=self.server_path)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\venv\pydyna\Lib\site-packages\ansys\dyna\core\pre\launcher.py", line 94, in launch_grpc
    process = subprocess.Popen(["python", "kwserver.py"], cwd=server_path, shell=True)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\t321242\.pyenv\pyenv-win\versions\3.11.4\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\t321242\.pyenv\pyenv-win\versions\3.11.4\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,

In airbag_deploy.py, line 58, 'airbag_solution = DynaSolution(hostname)', i.e. where an instance of the DynaSolution class is created, an error occurred.
Further tracing shows that at line 65,
"if (hostname.lower() == "localhost" or hostname == LOCALHOST) and not DynaSolution.grpc_local_server_on():, DynaSolution.", 
grpc_local_server_on() was returning False. I think this is what is causing this error.
I think False is returned because a timeout occurs at the GRPC server call in this method.

I checked the 50051 port on the machine running pre server with the Test-NetConnection command and got the following reply, so I think I am able to connect to the server.

ComputerName : localhost
RemoteAddress : 127.0.0.1
RemotePort : 50051
InterfaceAlias : Loopback Pseudo-Interface 1
SourceAddress : 127.0.0.1
TcpTestSucceeded : True

Why can't I get to the pre server from a python client?

**Comment by zhangzhanqun** [comment]
Hi kakemoto,

    It seems that the server can not be connected, I will try to find out where is the problem.
You can try to use the local pre server, please download the local server from https://github.com/ansys/pydyna/releases/download/v0.4.3/ansys-pydyna-pre-server.zip
and start the server according to the README.rst file in the package.

Please have a try, any problems please let me know.

Regards,
Zhanqun.

**Comment by kakemoto** [comment]
Hi Zhangzhanqun,

Thank you for the reply. I will try it as soon as possible.

**Comment by kakemoto** [comment]
Sorry for not responding for a while. I downloaded the pre server from the path you gave me and used it. At first I could not connect, but when I set localhost in the environment variable, it worked.
Therefore, we will close this matter.
Thank you very much for your cooperation in resolving my problem.
