### ISSUE TITLE
Fail to start PyDyna preprocessing server with python 3.11

### ISSUE THREAD

**Issue by rokamoto26** [ansys/pydyna#356]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

When pyDyna environment is set up with python 3.11, kwserver.py shows system error as follows.

(PyDyna_311_04) C:\pydyna\ansys-pydyna-pre-server>python kwserver.py
Traceback (most recent call last):
  File "C:\pydyna\ansys-pydyna-pre-server\kwserver.py", line 24, in <module>
    from keywordreader import KeywordReader as kp
SystemError: type Boost.Python.enum has the Py_TPFLAGS_HAVE_GC flag but has no traverse function

But It works with Python 3.10.

### 📝 Steps to reproduce

1. Install Client in User mode: python -m pip install ansys-dyna-core
2. Downloaded zip file blow and put unziped file into C:\pydyna\
https://github.com/ansys/pydyna/releases/download/v0.4.5/ansys-pydyna-pre-server.zip
3.  cd  C:\pydyna\ansys-pydyna-pre-server
4. run "python kwserver.py" in command prompt

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

2023R1, 2023R2, 2024R1

### 🐍 Which Python version are you using?

3.11

### 📦 Installed packages

```shell
ansys-api-dyna==0.3.5
ansys-dpf-core==0.10.1
ansys-dyna-core==0.4.5
anyio==4.2.0
argon2-cffi==23.1.0
argon2-cffi-bindings==21.2.0
arrow==1.3.0
asttokens==2.4.1
async-lru==2.0.4
attrs==23.2.0
Babel==2.14.0
beautifulsoup4==4.12.2
bleach==6.1.0
cachetools==5.3.2
certifi==2023.11.17
cffi==1.16.0
charset-normalizer==3.3.2
colorama==0.4.6
comm==0.2.1
contourpy==1.2.0
cycler==0.12.1
debugpy==1.8.0
decorator==5.1.1
defusedxml==0.7.1
executing==2.0.1
fastjsonschema==2.19.1
fonttools==4.47.0
fqdn==1.5.1
google-api-core==2.15.0
google-api-python-client==2.113.0
google-auth==2.26.1
google-auth-httplib2==0.2.0
googleapis-common-protos==1.62.0
grpcio==1.60.0
httplib2==0.22.0
idna==3.6
importlib-metadata==7.0.1
ipykernel==6.28.0
ipython==8.20.0
isoduration==20.11.0
jedi==0.19.1
Jinja2==3.1.3
joblib==1.3.2
json5==0.9.14
jsonpointer==2.4
jsonschema==4.20.0
jsonschema-specifications==2023.12.1
jupyter-events==0.9.0
jupyter-lsp==2.2.1
jupyter_client==8.6.0
jupyter_core==5.7.1
jupyter_server==2.12.3
jupyter_server_terminals==0.5.1
jupyterlab==4.0.10
jupyterlab_pygments==0.3.0
jupyterlab_server==2.25.2
kiwisolver==1.4.5
MarkupSafe==2.1.3
matplotlib==3.8.2
matplotlib-inline==0.1.6
mistune==3.0.2
nbclient==0.9.0
nbconvert==7.14.0
nbformat==5.9.2
nest-asyncio==1.5.8
notebook_shim==0.2.3
numpy==1.26.3
overrides==7.4.0
packaging==23.2
pandas==2.1.4
pandocfilters==1.5.0
parso==0.8.3
pillow==10.2.0
platformdirs==4.1.0
prometheus-client==0.19.0
prompt-toolkit==3.0.43
protobuf==3.20.3
psutil==5.9.7
pure-eval==0.2.2
pyasn1==0.5.1
pyasn1-modules==0.3.0
pycparser==2.21
Pygments==2.17.2
pyparsing==3.1.1
python-dateutil==2.8.2
python-json-logger==2.0.7
pytz==2023.3.post1
pywin32==306
pywinpty==2.0.12
PyYAML==6.0.1
pyzmq==25.1.2
referencing==0.32.1
requests==2.31.0
rfc3339-validator==0.1.4
rfc3986-validator==0.1.1
rpds-py==0.16.2
rsa==4.9
scikit-learn==1.3.2
scipy==1.11.4
Send2Trash==1.8.2
six==1.16.0
sniffio==1.3.0
soupsieve==2.5
stack-data==0.6.3
terminado==0.18.0
threadpoolctl==3.2.0
tinycss2==1.2.1
tornado==6.4
tqdm==4.66.1
traitlets==5.14.1
types-python-dateutil==2.8.19.20240106
tzdata==2023.4
uri-template==1.3.0
uritemplate==4.1.1
urllib3==2.1.0
wcwidth==0.2.13
webcolors==1.13
webencodings==0.5.1
websocket-client==1.7.0
zipp==3.17.0
```

**Comment by zhangzhanqun** [comment]
@rokamoto26 Thank you for your bug report. The boost.python package is mismatch with python3.11, It cause this issue, now the server package have been updated, please download it from https://github.com/ansys/pydyna/releases/download/v0.4.8/ansys-pydyna-pre-server.zip and try it again.

**Comment by rokamoto26** [comment]
@zhangzhanqun, Thank you for your comments. I confirmed the kwsever.py in the link you told me worked well.

But may I should raise another issue, when installing pydyna 0.40.14 on python3.11 with pip command, same error still appears as attached image. 
I confirmed python 3.10 doesn't cause a error for launching kwsever. 


![スクリーンショット 2024-03-28 162350](https://github.com/ansys/pydyna/assets/89230251/0e922b2b-05f1-467d-aa11-5888e87c83bf)

**Comment by yurynovozhilov** [comment]
@zhangzhanqun 
I can confirm that the new server can be started manually with the ```python.exe kwserver.py ```

However, if I then launch any test case of pydyna (https://dyna.docs.pyansys.com/version/stable/examples/Explicit/ball_plate.html#sphx-glr-examples-explicit-ball-plate-py for example), the method ```solution = launch_dynapre(ip = "localhost")``` forcefully downloads the ansys-pydyna-pre-server version with an error.

**Comment by zhangzhanqun** [comment]
@yurynovozhilov @rokamoto26 Thank you for your information, I have tried to fix this problem in new release version, please check the version v0.4.15 and try again.

**Comment by rokamoto26** [comment]
@zhangzhanqun Thank you for your support!  I confirm it works when I update to pydyna 0.40.15 and delete the existing server folder,  C:\Users\"Username"\AppData\Roaming\PYDYNA\ansys-pydyna-pre-server.
