### ISSUE TITLE
Perform a new minor release with ansys-api-dyna v0.4.0

### ISSUE THREAD

**Issue by RobPasMue** [ansys/pydyna#502]
Following https://github.com/ansys/ansys-api-dyna/pull/13 I performed a release on ansys-api-dyna. This is blocking for the entire PyAnsys ecosystem. Once https://github.com/ansys/pydyna/pull/501 is merged, we request you @ansys/pydyna maintainers to do a new minor release. This is urgent.

For more details see https://github.com/ansys/ansys-tools-protoc-helper/issues/29#issuecomment-2286136182

**Comment by RobPasMue** [comment]
@zhangzhanqun @wenhuiuy @kanthadya - please respond

**Comment by zhangzhanqun** [comment]
@RobPasMue what I should do is to build a new release v0.4.1, right?

**Comment by RobPasMue** [comment]
I recommend doing a new minor version IMO, so v0.5.0

**Comment by zhangzhanqun** [comment]
Hi @RobPasMue ,I tried to release v0.5.0 from Releases->Draft a new release->Choose a tag(v0.5.0)->Publish release, but it seems that it is incorrect, there are no .whl and .tar.gz files in Assets, could you please give me some details on how to release this project from github-actions?

**Comment by RobPasMue** [comment]
Please follow the instructions on how to release... https://dev.docs.pyansys.com/how-to/releasing.html

These are standard for all projects. You should be familiar with them. In your case you are releasing a minor version (0.5) so follow the instructions accordingly (create a release/0.5 branch, modify the needed version references, create tag from release branch...)

**Comment by zhangzhanqun** [comment]
Hi @RobPasMue, thank you for your information, release 0.5.0 have been created, please check it.

**Comment by RobPasMue** [comment]
Hi @zhangzhanqun - I meant that you should do a release 0.5.0 on the PyDyna repo, not on the ansys-api-dyna one... Please read this issue's description. 

Perform a new ansys-dyna-core release whenever possible.

**Comment by zhangzhanqun** [comment]
Hi @RobPasMue sorry for that, I perform a new pydyna release and it create a pull request, please check if it is correct, it is my first time to perform release, so any problems please tell me.

**Comment by RobPasMue** [comment]
Release was created successfully :) No need to create a PR - just let the branch on its own. I closed it for you this time. Thanks a lot @zhangzhanqun and congrats on your first release!
