### ISSUE TITLE
ControlTimestep class missing

### ISSUE THREAD

**Issue by MeenaBytes** [ansys/pydyna#589]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

Hello,

I was trying to read a LS-DYNA file with control time step card (*CONTROL_TIMESTEP) but dynalib throws error saying ControlTimestep not defined in ansys.dyna.keywords.keyword_classes.

### 📝 Steps to reproduce

NA

### 💻 Which operating system are you using?

Windows

### 🐍 Which Python version are you using?

3.10

### 📦 Installed packages

```shell
--
```

**Comment by RaphaelHeiniger** [comment]
This will be fixed once CONTROL_TIMESTEP and CONTROL_TIME_STEP (#629) is merged to main.
